const types = {
	FETCH_POSTS: "FETCH_POSTS",
	CREATE_POST: "CREATE_POST", // Create
	FETCH_POST: "FETCH_POST", // Read
	UPDATE_POST: "UPDATE_POST", // Update
	DELETE_POST: "DELETE_POST", // Delete
	TOGGLE_MODAL_VISIBILITY: "TOGGLE_MODAL_VISIBILITY",
	GENERATE_CARDS: "GENERATE_CARDS",
};

export default types;
