const types = {
	FETCH_CARDS: "FETCH_CARDS",
	CREATE_CARD: "CREATE_CARD", // Create
	FETCH_CARD: "FETCH_CARD", // Read
	UPDATE_CARD: "UPDATE_CARD", // Update
	DELETE_CARD: "DELETE_CARD", // Delete
	DELETE_ALL_CARDS: "DELETE_ALL_CARDS", // Delete
	TOGGLE_MODAL_VISIBILITY: "TOGGLE_MODAL_VISIBILITY",
};

export default types;
