const types = {
	FETCH_CARDS: "FETCH_CARDS",
	CREATE_CARD: "CREATE_CARD", // Create
	FETCH_CARD: "FETCH_CARD", // Read
	UPDATE_CARD: "UPDATE_CARD", // Update
	DELETE_CARD: "DELETE_CARD", // Delete
	TOGGLE_MODAL_VISIBILITY: "TOGGLE_MODAL_VISIBILITY",
	GENERATE_CARDS: "GENERATE_CARDS",
};

export default types;
